name: Phpunit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.5', '5.6', '7.0', '7.2', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, json

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --prefer-source

      - name: Run test suite
        run: composer run-script test
